### ISSUE TITLE
It was not possible to parse your key

### ISSUE THREAD

**Issue by onli** [portier/portier-php#2]
I'm currently implementing a plugin for a blogging engine, of course using your client, and am getting the following error in the last step, trying to validate an id_token:

```
<br />
<b>Fatal error</b>:  Uncaught InvalidArgumentException: It was not possible to parse your key, reason: error:0906D064:PEM routines:PEM_read_bio:bad base64 decode in /var/www/virtual/onli/html/s9y_dev/plugins/serendipity_event_browserid/vendor/lcobucci/jwt/src/Signer/Rsa.php:60
Stack trace:
#0 /var/www/virtual/onli/html/s9y_dev/plugins/serendipity_event_browserid/vendor/lcobucci/jwt/src/Signer/Rsa.php(45): Lcobucci\JWT\Signer\Rsa-&gt;validateKey(false)
#1 /var/www/virtual/onli/html/s9y_dev/plugins/serendipity_event_browserid/vendor/lcobucci/jwt/src/Signer/BaseSigner.php(42): Lcobucci\JWT\Signer\Rsa-&gt;doVerify('\xB3\xDF\xDA\xE5\x81[_E\xB5!\xF0%B-\xEE...', 'eyJhbGciOiJSUzI...', false)
#2 /var/www/virtual/onli/html/s9y_dev/plugins/serendipity_event_browserid/vendor/lcobucci/jwt/src/Signature.php(47): Lcobucci\JWT\Signer\BaseSigner-&gt;verify('\xB3\xDF\xDA\xE5\x81[_E\xB5!\xF0%B-\xEE...', 'eyJhbGciOiJSUzI...', Object(Lcobucci\JWT\Signer\Key))
#3 /var/www/virtual/onli/html/s9y_dev/plugins/serendipity_event_browserid/vendor/lcobucci/jwt/src/Tok in <b>/var/www/virtual/onli/html/s9y_dev/plugins/serendipity_event_browserid/vendor/lcobucci/jwt/src/Signer/Rsa.php</b> on line <b>60</b><br />
```

I assume that this is sufficiently deep in the client code itself that it is unlikely my use of it is the problem, but I'll have a second look now. Is this code currently in use, and does it work with the current broker?

**Comment by onli** [comment]
I went a bit further into the code. The error is coming from the token verification in [line 102 of the Client](https://github.com/portier/portier-php/blob/cd82174861745c915d1117577eee772f1bebbd10/src/Client.php#L102):

```
if (!$token->verify(
    new \Lcobucci\JWT\Signer\Rsa\Sha256(),
    self::parseJwk($publicKey)
)) {
    throw new \Exception('Token signature did not validate');
}
```

My best guess is that the parse_jwk function is not correct (maybe the currently used key on broker.portier.io triggered a bug in it?). It in any case is very low-level. But it is strange that the creation of \Lcobucci\JWT\Signer\Key does not fail, the error is only in the next step.

**Comment by onli** [comment]
Additional observation/question (then I'm through for today, I did not resolve it): This is the string that is produced in `parseJwk`:

```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvjgwqeWxlOBywlH0JCrCxahbN8OW4g2/uwFQAAzXXw/e5SUnkBf7RFJwKBmD9akX+Lfjs5tbyiqOkOT9v6L4IHMCYCl+ksPgmyJIrB/0BFQvIwxDKw7rS3UuZEiGgjBu5VoOO0pn8X0D3qCtbYR791J3vzG89X7FRnZcZ6RuHGdktrBeCCQRc9hityiqVLMErljfu7GZOIzwbUzpt+neiQUNI/JcvFXR7arZO5H5UN7Pl0yM09t67NvSDtTrdPx2sDECKYtEuZvM4BuBlh6O9bHoyvryH4ia7VsS4Zlpe3rvuFtIq5vK4eJ+gqdVWK6laktWvr+zzmV+RZHD6rcI7QIDAQAB
-----END PUBLIC KEY-----
```

Isn't there normally a == at the end?
